import {
	AccountTree,
	AdminPanelSettings,
	AllInclusive,
	Analytics,
	Architecture,
	AutoAwesome,
	Code,
	ContactSupport,
	DesignServices,
	Lan,
	Laptop,
	Science,
	Security,
	Smartphone,
	SportsEsports,
	Storage,
} from '@mui/icons-material';

export const muiTechnologies = [
	{
		icon: AutoAwesome,
		label: 'AI/ML',
		value: 'ai-ml',
		color: '#BE43A8',
	},
	{
		icon: Code,
		label: 'C',
		value: 'c',
		color: '#00A98F',
	},
	{
		icon: Smartphone,
		label: 'Mobile',
		value: 'mobile',
		color: '#E55A89',
	},
	{
		icon: Science,
		label: 'Testing',
		value: 'testing',
		color: '#00B5AD',
	},
	{
		icon: AllInclusive,
		label: 'DevOps',
		value: 'devops',
		color: '#4AB8E7',
	},
	{
		icon: AdminPanelSettings,
		label: 'Admin',
		value: 'admin',
		color: '#43A0E5',
	},
	{
		icon: DesignServices,
		label: 'UX/UI',
		value: 'ux-ui',
		color: '#F4A23A',
	},
	{
		icon: AccountTree,
		label: 'PM',
		value: 'pm',
		color: '#43C1B5',
	},
	{
		icon: SportsEsports,
		label: 'Game',
		value: 'game',
		color: '#E55A70',
	},
	{
		icon: Analytics,
		label: 'Analytics',
		value: 'analytics',
		color: '#677BC8',
	},
	{
		icon: Security,
		label: 'Security',
		value: 'security',
		color: '#4369E5',
	},
	{
		icon: Storage,
		label: 'Data',
		value: 'data',
		color: '#4CAF50',
	},
	{
		icon: ContactSupport,
		label: 'Support',
		value: 'support',
		color: '#A456D8',
	},
	{
		icon: Lan,
		label: 'ERP',
		value: 'erp',
		color: '#4FC0E8',
	},
	{
		icon: Architecture,
		label: 'Architecture',
		value: 'architecture',
		color: '#F57C00',
	},
	{
		icon: Laptop,
		label: 'Other',
		value: 'other',
		color: '#E55AB4',
	},
] as const;

export const svgTechnologies = [
	{
		icon: 'dot-net.svg',
		label: '.NET',
		value: 'dot-net',
		color: '#9343BE',
	},
	{
		icon: 'go-plain.svg',
		label: 'Go',
		value: 'go',
		color: '#4FC0E8',
	},
	{
		icon: 'html5-plain.svg',
		label: 'HTML5',
		value: 'html5',
		color: '#E44D26',
	},
	{
		icon: 'java-plain.svg',
		label: 'Java',
		value: 'java',
		color: '#E04F4F',
	},
	{
		icon: 'javascript.svg',
		label: 'JavaScript',
		value: 'javascript',
		color: '#F7DF1E',
	},
	{
		icon: 'php-plain.svg',
		label: 'PHP',
		value: 'php',
		color: '#6181B6',
	},
	{
		icon: 'python-plain.svg',
		label: 'Python',
		value: 'python',
		color: '#3770A3',
	},
	{
		icon: 'ruby-plain.svg',
		label: 'Ruby',
		value: 'ruby',
		color: '#CC342D',
	},
	{
		icon: 'scala-plain.svg',
		label: 'Scala',
		value: 'scala',
		color: '#E15858',
	},
] as const;
